name: build-paper

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - paper/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        uses: openjournals/joss-papers@v1
