on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: Deploy Pkgdown Site

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages  # Or 'main' if you're using main/docs setup
          folder: docs  # ✅ Deploys the already-built site
          clean: false
